delete PropertyValuesForNode
delete PropertyValuesForPage
delete PropertyValuesForGraphic
delete NextGraphicObject

delete BuiltItem

delete FADSField
delete FADSScreen
delete FADSArea

delete Datalink
delete FADSConstraintdependency
delete computedobjectdependency
delete CodeScriptAssignment
delete DataExchangeElement
delete DataExchangeHistory
delete GraphicObject
delete NavigationNode
delete PageHistory
delete Page
delete NavigationHistory
delete Navigation
delete CurrencyRoundingCode
delete Product

delete ImageInfo
delete ImageObject


delete ValueListItem
delete ValueList
delete holiday
delete codescripttestcasevalues
delete codescripttestcase
delete codescriptparameters
delete codescriptbasescriptxref
delete codescript
delete basecodescript


delete DeveloperRoleXref
delete DeveloperRole
delete NetworkLogin 
delete DeveloperName


delete Enum_PageType
delete Enum_NodeType
delete Enum_Jurisdiction
delete Enum_NavigationType
delete Enum_AttachmentLinkTextOption
delete Enum_EntityLoopEntity
delete Enum_FormatDateOption
delete Enum_CodeType
delete Enum_GraphicObjectType
delete Enum_SpecialTextType
delete Enum_GroupOverflow
delete Enum_AnchorPosition
delete Enum_FormatNegativeOption
delete Enum_FormatZeroOption
delete Enum_GroupRepetitionDirection
delete Enum_OverscoreUnderscoreCharacter
delete Enum_PaperOrientation
delete Enum_PaperSize
delete Enum_SpecialHeaderNodeFunction
delete Enum_RegularExpression

delete Enterprise_Information