//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaxAppClientAsyncService", CallbackContract=typeof(ITaxAppClientAsyncServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ITaxAppClientAsyncService
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITaxAppClientAsyncService/Join")]
    void Join(string name);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientAsyncService/Join")]
    System.IAsyncResult BeginJoin(string name, System.AsyncCallback callback, object asyncState);
    
    void EndJoin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/ITaxAppClientAsyncService/Leave")]
    void Leave(string name);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, IsInitiating=false, AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientAsyncService/Leave")]
    System.IAsyncResult BeginLeave(string name, System.AsyncCallback callback, object asyncState);
    
    void EndLeave(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/ITaxAppClientAsyncService/UpdatePages")]
    void UpdatePages(int[] updatedPages);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientAsyncService/UpdatePages")]
    System.IAsyncResult BeginUpdatePages(int[] updatedPages, System.AsyncCallback callback, object asyncState);
    
    void EndUpdatePages(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITaxAppClientAsyncServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITaxAppClientAsyncService/PageUpdate")]
    void PageUpdate(int[] updatedPages);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientAsyncService/PageUpdate")]
    System.IAsyncResult BeginPageUpdate(int[] updatedPages, System.AsyncCallback callback, object asyncState);
    
    void EndPageUpdate(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITaxAppClientAsyncService/ServerDisconnected")]
    void ServerDisconnected();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientAsyncService/ServerDisconnected")]
    System.IAsyncResult BeginServerDisconnected(System.AsyncCallback callback, object asyncState);
    
    void EndServerDisconnected(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITaxAppClientAsyncServiceChannel : ITaxAppClientAsyncService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TaxAppClientAsyncServiceClient : System.ServiceModel.DuplexClientBase<ITaxAppClientAsyncService>, ITaxAppClientAsyncService
{
    
    public TaxAppClientAsyncServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public TaxAppClientAsyncServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public TaxAppClientAsyncServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientAsyncServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientAsyncServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Join(string name)
    {
        base.Channel.Join(name);
    }
    
    public System.IAsyncResult BeginJoin(string name, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginJoin(name, callback, asyncState);
    }
    
    public void EndJoin(System.IAsyncResult result)
    {
        base.Channel.EndJoin(result);
    }
    
    public void Leave(string name)
    {
        base.Channel.Leave(name);
    }
    
    public System.IAsyncResult BeginLeave(string name, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLeave(name, callback, asyncState);
    }
    
    public void EndLeave(System.IAsyncResult result)
    {
        base.Channel.EndLeave(result);
    }
    
    public void UpdatePages(int[] updatedPages)
    {
        base.Channel.UpdatePages(updatedPages);
    }
    
    public System.IAsyncResult BeginUpdatePages(int[] updatedPages, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdatePages(updatedPages, callback, asyncState);
    }
    
    public void EndUpdatePages(System.IAsyncResult result)
    {
        base.Channel.EndUpdatePages(result);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaxAppClientService")]
public interface ITaxAppClientService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/GetClientAndLocatorInfo", ReplyAction="http://tempuri.org/ITaxAppClientService/GetClientAndLocatorInfoResponse")]
    TaxAppClient.WCFService.CliInfo[] GetClientAndLocatorInfo();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/GetClientAndLocatorInfo", ReplyAction="http://tempuri.org/ITaxAppClientService/GetClientAndLocatorInfoResponse")]
    System.IAsyncResult BeginGetClientAndLocatorInfo(System.AsyncCallback callback, object asyncState);
    
    TaxAppClient.WCFService.CliInfo[] EndGetClientAndLocatorInfo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/GetListOfStrings", ReplyAction="http://tempuri.org/ITaxAppClientService/GetListOfStringsResponse")]
    string[] GetListOfStrings(string messageType);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/GetListOfStrings", ReplyAction="http://tempuri.org/ITaxAppClientService/GetListOfStringsResponse")]
    System.IAsyncResult BeginGetListOfStrings(string messageType, System.AsyncCallback callback, object asyncState);
    
    string[] EndGetListOfStrings(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/RunMethodByMessageTypeReturnInt", ReplyAction="http://tempuri.org/ITaxAppClientService/RunMethodByMessageTypeReturnIntResponse")]
    int RunMethodByMessageTypeReturnInt(string messageType, string parameters);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/RunMethodByMessageTypeReturnInt", ReplyAction="http://tempuri.org/ITaxAppClientService/RunMethodByMessageTypeReturnIntResponse")]
    System.IAsyncResult BeginRunMethodByMessageTypeReturnInt(string messageType, string parameters, System.AsyncCallback callback, object asyncState);
    
    int EndRunMethodByMessageTypeReturnInt(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/GetRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/GetRecordsResponse")]
    TaxAppClient.WCFService.LORecord[] GetRecords(int locatorID, short year, int recordLineage, int pageID, int graphicID, int parentGraphicID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/GetRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/GetRecordsResponse")]
    System.IAsyncResult BeginGetRecords(int locatorID, short year, int recordLineage, int pageID, int graphicID, int parentGraphicID, System.AsyncCallback callback, object asyncState);
    
    TaxAppClient.WCFService.LORecord[] EndGetRecords(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/SetRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/SetRecordsResponse")]
    TaxAppClient.WCFService.LORecord[] SetRecords(TaxAppClient.WCFService.LORecord[] records);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/SetRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/SetRecordsResponse")]
    System.IAsyncResult BeginSetRecords(TaxAppClient.WCFService.LORecord[] records, System.AsyncCallback callback, object asyncState);
    
    TaxAppClient.WCFService.LORecord[] EndSetRecords(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientService/DeleteRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/DeleteRecordsResponse")]
    bool DeleteRecords(TaxAppClient.WCFService.LORecord[] records);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientService/DeleteRecords", ReplyAction="http://tempuri.org/ITaxAppClientService/DeleteRecordsResponse")]
    System.IAsyncResult BeginDeleteRecords(TaxAppClient.WCFService.LORecord[] records, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteRecords(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITaxAppClientServiceChannel : ITaxAppClientService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TaxAppClientServiceClient : System.ServiceModel.ClientBase<ITaxAppClientService>, ITaxAppClientService
{
    
    public TaxAppClientServiceClient()
    {
    }
    
    public TaxAppClientServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaxAppClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TaxAppClient.WCFService.CliInfo[] GetClientAndLocatorInfo()
    {
        return base.Channel.GetClientAndLocatorInfo();
    }
    
    public System.IAsyncResult BeginGetClientAndLocatorInfo(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetClientAndLocatorInfo(callback, asyncState);
    }
    
    public TaxAppClient.WCFService.CliInfo[] EndGetClientAndLocatorInfo(System.IAsyncResult result)
    {
        return base.Channel.EndGetClientAndLocatorInfo(result);
    }
    
    public string[] GetListOfStrings(string messageType)
    {
        return base.Channel.GetListOfStrings(messageType);
    }
    
    public System.IAsyncResult BeginGetListOfStrings(string messageType, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetListOfStrings(messageType, callback, asyncState);
    }
    
    public string[] EndGetListOfStrings(System.IAsyncResult result)
    {
        return base.Channel.EndGetListOfStrings(result);
    }
    
    public int RunMethodByMessageTypeReturnInt(string messageType, string parameters)
    {
        return base.Channel.RunMethodByMessageTypeReturnInt(messageType, parameters);
    }
    
    public System.IAsyncResult BeginRunMethodByMessageTypeReturnInt(string messageType, string parameters, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRunMethodByMessageTypeReturnInt(messageType, parameters, callback, asyncState);
    }
    
    public int EndRunMethodByMessageTypeReturnInt(System.IAsyncResult result)
    {
        return base.Channel.EndRunMethodByMessageTypeReturnInt(result);
    }
    
    public TaxAppClient.WCFService.LORecord[] GetRecords(int locatorID, short year, int recordLineage, int pageID, int graphicID, int parentGraphicID)
    {
        return base.Channel.GetRecords(locatorID, year, recordLineage, pageID, graphicID, parentGraphicID);
    }
    
    public System.IAsyncResult BeginGetRecords(int locatorID, short year, int recordLineage, int pageID, int graphicID, int parentGraphicID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRecords(locatorID, year, recordLineage, pageID, graphicID, parentGraphicID, callback, asyncState);
    }
    
    public TaxAppClient.WCFService.LORecord[] EndGetRecords(System.IAsyncResult result)
    {
        return base.Channel.EndGetRecords(result);
    }
    
    public TaxAppClient.WCFService.LORecord[] SetRecords(TaxAppClient.WCFService.LORecord[] records)
    {
        return base.Channel.SetRecords(records);
    }
    
    public System.IAsyncResult BeginSetRecords(TaxAppClient.WCFService.LORecord[] records, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSetRecords(records, callback, asyncState);
    }
    
    public TaxAppClient.WCFService.LORecord[] EndSetRecords(System.IAsyncResult result)
    {
        return base.Channel.EndSetRecords(result);
    }
    
    public bool DeleteRecords(TaxAppClient.WCFService.LORecord[] records)
    {
        return base.Channel.DeleteRecords(records);
    }
    
    public System.IAsyncResult BeginDeleteRecords(TaxAppClient.WCFService.LORecord[] records, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteRecords(records, callback, asyncState);
    }
    
    public bool EndDeleteRecords(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteRecords(result);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaxAppClientServiceMTOM")]
public interface ITaxAppClientServiceMTOM
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxAppClientServiceMTOM/RequestBinary", ReplyAction="http://tempuri.org/ITaxAppClientServiceMTOM/RequestBinaryResponse")]
    byte[] RequestBinary(string appName, string fileName);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITaxAppClientServiceMTOM/RequestBinary", ReplyAction="http://tempuri.org/ITaxAppClientServiceMTOM/RequestBinaryResponse")]
    System.IAsyncResult BeginRequestBinary(string appName, string fileName, System.AsyncCallback callback, object asyncState);
    
    byte[] EndRequestBinary(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITaxAppClientServiceMTOMChannel : ITaxAppClientServiceMTOM, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TaxAppClientServiceMTOMClient : System.ServiceModel.ClientBase<ITaxAppClientServiceMTOM>, ITaxAppClientServiceMTOM
{
    
    public TaxAppClientServiceMTOMClient()
    {
    }
    
    public TaxAppClientServiceMTOMClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaxAppClientServiceMTOMClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientServiceMTOMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxAppClientServiceMTOMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public byte[] RequestBinary(string appName, string fileName)
    {
        return base.Channel.RequestBinary(appName, fileName);
    }
    
    public System.IAsyncResult BeginRequestBinary(string appName, string fileName, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRequestBinary(appName, fileName, callback, asyncState);
    }
    
    public byte[] EndRequestBinary(System.IAsyncResult result)
    {
        return base.Channel.EndRequestBinary(result);
    }
}
namespace TaxAppClient.WCFService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CliInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxAppClient.WCFService")]
    public partial class CliInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClientIDField;
        
        private string ClientNameField;
        
        private TaxAppClient.WCFService.LocInfo[] LocatorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName
        {
            get
            {
                return this.ClientNameField;
            }
            set
            {
                this.ClientNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxAppClient.WCFService.LocInfo[] Locators
        {
            get
            {
                return this.LocatorsField;
            }
            set
            {
                this.LocatorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxAppClient.WCFService")]
    public partial class LocInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LocatorIDField;
        
        private string NameField;
        
        private short YearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocatorID
        {
            get
            {
                return this.LocatorIDField;
            }
            set
            {
                this.LocatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LORecord", Namespace="http://schemas.datacontract.org/2004/07/TaxAppClient.WCFService")]
    public partial class LORecord : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte DataSourceUsedField;
        
        private byte DataTypeField;
        
        private int GraphicObjectIDField;
        
        private bool IsComputedFieldField;
        
        private int LocatorIDField;
        
        private int PageIDField;
        
        private int ParentGraphicIDField;
        
        private short ProductYearField;
        
        private int RecordIDField;
        
        private int RecordLineageField;
        
        private bool RecordWasAddedField;
        
        private bool RecordWasDeletedField;
        
        private short RowDisplayOrderField;
        
        private TaxAppClient.WCFService.LOValue[] ValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DataSourceUsed
        {
            get
            {
                return this.DataSourceUsedField;
            }
            set
            {
                this.DataSourceUsedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DataType
        {
            get
            {
                return this.DataTypeField;
            }
            set
            {
                this.DataTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GraphicObjectID
        {
            get
            {
                return this.GraphicObjectIDField;
            }
            set
            {
                this.GraphicObjectIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComputedField
        {
            get
            {
                return this.IsComputedFieldField;
            }
            set
            {
                this.IsComputedFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocatorID
        {
            get
            {
                return this.LocatorIDField;
            }
            set
            {
                this.LocatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageID
        {
            get
            {
                return this.PageIDField;
            }
            set
            {
                this.PageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentGraphicID
        {
            get
            {
                return this.ParentGraphicIDField;
            }
            set
            {
                this.ParentGraphicIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ProductYear
        {
            get
            {
                return this.ProductYearField;
            }
            set
            {
                this.ProductYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordID
        {
            get
            {
                return this.RecordIDField;
            }
            set
            {
                this.RecordIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordLineage
        {
            get
            {
                return this.RecordLineageField;
            }
            set
            {
                this.RecordLineageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RecordWasAdded
        {
            get
            {
                return this.RecordWasAddedField;
            }
            set
            {
                this.RecordWasAddedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RecordWasDeleted
        {
            get
            {
                return this.RecordWasDeletedField;
            }
            set
            {
                this.RecordWasDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short RowDisplayOrder
        {
            get
            {
                return this.RowDisplayOrderField;
            }
            set
            {
                this.RowDisplayOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxAppClient.WCFService.LOValue[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOValue", Namespace="http://schemas.datacontract.org/2004/07/TaxAppClient.WCFService")]
    public partial class LOValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BooleanValueField;
        
        private byte DataSourceField;
        
        private System.DateTime DateLastSavedField;
        
        private System.DateTime DateTimeValueField;
        
        private decimal FractionValueField;
        
        private decimal NumericValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BooleanValue
        {
            get
            {
                return this.BooleanValueField;
            }
            set
            {
                this.BooleanValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DataSource
        {
            get
            {
                return this.DataSourceField;
            }
            set
            {
                this.DataSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastSaved
        {
            get
            {
                return this.DateLastSavedField;
            }
            set
            {
                this.DateLastSavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeValue
        {
            get
            {
                return this.DateTimeValueField;
            }
            set
            {
                this.DateTimeValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FractionValue
        {
            get
            {
                return this.FractionValueField;
            }
            set
            {
                this.FractionValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumericValue
        {
            get
            {
                return this.NumericValueField;
            }
            set
            {
                this.NumericValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}
